package corbaConversion;


/**
* corbaConversion/IConversionRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* vendredi 1 décembre 2023 10 h 33 WAT
*/

public interface IConversionRemoteOperations 
{
  double conversionMontant (double mt);
} // interface IConversionRemoteOperations
